const U = require("./report_utils.js");
const {
  H1, H2, H3, P, bullet, b, t, it, code, caption, imgRatio, makeTable, ref,
  Document, Packer, Paragraph, TextRun, AlignmentType, LevelFormat, HeadingLevel,
  BorderStyle, Header, Footer, PageNumber, ACCENT
} = U;

const children = [];

// ============================ PORTADA ============================
children.push(new Paragraph({ spacing: { before: 1400, after: 0 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: "Universidad Nacional Autónoma de México", size: 24, color: "555555" })] }));
children.push(new Paragraph({ spacing: { after: 600 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: "Facultad de Ingeniería  ·  Análisis y Procesamiento Inteligente de Textos  ·  Semestre 2026-2", size: 22, color: "777777" })] }));
children.push(new Paragraph({ spacing: { before: 200, after: 120 }, alignment: AlignmentType.CENTER,
  border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: ACCENT, space: 8 } },
  children: [new TextRun({ text: "Clasificación Multiclase de Patrones Lingüísticos en Trastornos de Salud Mental", bold: true, size: 38, color: "000000" })] }));
children.push(new Paragraph({ spacing: { before: 120, after: 700 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: "Un sistema clásico de Recuperación de Información basado en el Modelo de Espacio Vectorial, similitud coseno y autómatas de estados finitos", italics: true, size: 24, color: "555555" })] }));
children.push(new Paragraph({ spacing: { after: 80 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Autores", bold: true, size: 24 })] }));
["[ Nombre del integrante 1 ]", "[ Nombre del integrante 2 ]", "[ Nombre del integrante 3 ]"].forEach(n =>
  children.push(new Paragraph({ spacing: { after: 40 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: n, size: 22 })] })));
children.push(new Paragraph({ spacing: { before: 200, after: 40 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: "Facultad de Ingeniería, Universidad Nacional Autónoma de México", size: 20, color: "555555" })] }));
children.push(new Paragraph({ spacing: { after: 1000 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: "Fecha: ____ / ____ / 2026", size: 20, color: "555555" })] }));
children.push(new Paragraph({ children: [new TextRun("")], pageBreakBefore: true }));

// ============================ ABSTRACT ============================
children.push(H1("Resumen (Abstract)"));
children.push(P([ b("Antecedentes. "), t("Los trastornos de salud mental —en particular la depresión, la ideación suicida y la esquizofrenia— constituyen un problema de salud pública de primer orden: la depresión afecta a cerca de 280 millones de personas en el mundo y se asocia de manera directa con el suicidio y con una elevada carga de discapacidad. Las plataformas sociales como Reddit generan a diario un enorme volumen de texto donde las personas expresan su estado emocional, lo que ha convertido a estos foros en una fuente valiosa para la detección temprana de señales de riesgo mediante Procesamiento de Lenguaje Natural (PLN).") ]));
children.push(P([ b("Objetivo. "), t("Construir y evaluar un sistema de clasificación multiclase —Neutral, Depresión, Ideación Suicida y Esquizofrenia— fundamentado exclusivamente en técnicas clásicas de Recuperación de Información (RI), sin emplear modelos de aprendizaje automático entrenados ni representaciones neuronales, y valorar de forma crítica el desempeño y las limitaciones de dichas técnicas en un escenario de cribado de riesgo.") ]));
children.push(P([ b("Métodos. "), t("Se unificó y balanceó un corpus de 18 159 publicaciones de Reddit etiquetadas en cuatro clases. El texto se representó mediante el Modelo de Espacio Vectorial con ponderación TF-IDF implementada desde cero sobre NumPy. Cada trastorno se modeló como un centroide (clasificación de Rocchio) y los documentos se asignaron por similitud coseno con una regla de argmax y un umbral de rechazo hacia la clase Neutral. Se incorporó extracción de información mediante expresiones regulares y un transductor de estados finitos para normalizar la duración de los síntomas. La evaluación empleó matriz de confusión, precisión, exhaustividad (recall) y F1; el desempeño se validó mediante validación cruzada estratificada de cinco iteraciones y se contrastó con un modelo base de Naïve Bayes Multinomial, ambos implementados desde cero.") ]));
children.push(P([ b("Resultados. "), t("El sistema alcanzó un F1 macro de 0.79 sobre el conjunto de prueba. La clase Depresión obtuvo el mejor desempeño (F1 = 0.89), comparable a referentes de la literatura que emplean métodos supervisados. Un análisis dirigido sobre la clase Ideación Suicida —la de mayor costo clínico— reveló que sus falsos negativos correspondían a textos extremadamente cortos; la adopción de un umbral específico por clase elevó su exhaustividad de 0.72 a 0.79, recuperando 103 publicaciones de riesgo, con una caída marginal del F1 macro global.") ]));
children.push(P([ b("Conclusiones. "), t("Las técnicas clásicas de RI ofrecen una línea base interpretable, reproducible y computacionalmente económica para el cribado de trastornos de salud mental en texto, con un desempeño útil pese a no usar aprendizaje profundo. El estudio confirma la hipótesis, documenta las limitaciones intrínsecas del modelo (fragilidad ante textos cortos, pérdida de contexto y solapamiento de vocabulario) y subraya el papel central de la exhaustividad como métrica de optimización en contextos de riesgo.") ], { after: 120 }));
children.push(P([ b("Palabras clave: "), it("recuperación de información; modelo de espacio vectorial; TF-IDF; similitud coseno; clasificación de Rocchio; marcadores lingüísticos; salud mental; detección de depresión; ideación suicida; autómatas finitos; transductores de estados finitos.") ]));
children.push(new Paragraph({ children: [new TextRun("")], pageBreakBefore: true }));

// ============================ 1. INTRODUCCIÓN ============================
children.push(H1("1. Introducción"));
children.push(H2("1.1 Antecedentes"));
children.push(P("Detrás de cada publicación en un foro de salud mental hay una persona. Frases como «llevo tres años sintiéndome vacío» o «le doy una semana más» aparecen a diario en comunidades como r/depression o r/SuicideWatch. Para un lector humano el tono de riesgo resulta evidente; para una máquina, ese mismo texto es solo una secuencia de caracteres. El reto de este proyecto es construir un sistema que, sin «comprender» el lenguaje en sentido humano, se aproxime a esa intuición empleando únicamente la geometría de las palabras."));
children.push(P("El interés por detectar trastornos mentales a partir de texto en redes sociales no es nuevo. Trabajos pioneros mostraron que es posible predecir episodios depresivos a partir de la actividad en Twitter (De Choudhury et al., 2013) y que existen marcadores lingüísticos asociados a distintos trastornos (Coppersmith et al., 2014). Reddit, en particular, se ha consolidado como una fuente privilegiada: su organización en subreddits temáticos y el uso de cuentas anónimas favorecen la autodivulgación, lo que produce corpus ricos en expresiones espontáneas de malestar (Bucur y Dinu, 2020). Sobre estos datos, Tadesse et al. (2019) alcanzaron un F1 de 0.93 en la detección de depresión, y diversos sistemas de detección de ideación suicida combinando TF-IDF con clasificadores han reportado exactitudes superiores al 90 %."));
children.push(P("Este proyecto se sitúa deliberadamente un paso atrás de esos sistemas: en lugar de aplicar aprendizaje supervisado o modelos neuronales, reconstruye desde cero la maquinaria clásica que sustenta a los motores de búsqueda y a muchos de aquellos clasificadores —la ponderación TF-IDF y la similitud coseno— para comprender de primera mano su funcionamiento, su poder y sus límites."));

children.push(H2("1.2 Motivación"));
children.push(H3("1.2.1 Motivación social"));
children.push(P("Los trastornos de salud mental están ampliamente subdiagnosticados. Muchas personas en crisis expresan su malestar en línea antes —o en lugar de— acudir a un profesional, y con frecuencia dejan señales detectables en su escritura (Teferra et al., 2024). Un sistema de cribado automático, aun siendo imperfecto, puede ayudar a priorizar la atención y a señalar publicaciones que merecen revisión humana, contribuyendo además a reducir el estigma al ofrecer una valoración objetiva y no enjuiciadora. En este escenario, dejar pasar un caso de riesgo (un falso negativo) es mucho más grave que generar una falsa alarma, principio que guiará nuestras decisiones de diseño y evaluación."));
children.push(H3("1.2.2 Motivación académica"));
children.push(P([ t("La asignatura persigue que el estudiante comprenda la matemática que sustenta las bibliotecas modernas de PLN. Por ello el sistema se construye «desde cero»: las matrices TF e IDF, la similitud coseno y las métricas de evaluación se implementan con operaciones de NumPy, sin recurrir a "), code("scikit-learn"), t(" en el núcleo del modelo. El objetivo pedagógico es doble: demostrar el funcionamiento interno del Modelo de Espacio Vectorial y, sobre todo, exponer y explicar sus límites cuando se le confronta con datos reales y ruidosos.") ]));

children.push(H2("1.3 Hipótesis"));
children.push(P([ b("Hipótesis principal. "), it("Es posible clasificar publicaciones de redes sociales en cuatro categorías de salud mental (Neutral, Depresión, Ideación Suicida y Esquizofrenia) con un desempeño útil —medido por F1 y, en particular, por la exhaustividad de las clases de riesgo— empleando exclusivamente técnicas clásicas de Recuperación de Información (TF-IDF, centroides y similitud coseno), sin modelos de aprendizaje automático entrenados.") ]));
children.push(P([ b("Hipótesis secundaria. "), it("Las limitaciones del desempeño no serán uniformes entre clases, sino que se concentrarán en fenómenos lingüísticos identificables (textos cortos, vocabulario compartido, negación), de manera que un análisis de errores permita mejoras dirigidas dentro del mismo marco clásico.") ]));

children.push(H2("1.4 Descripción de la estructura"));
children.push(P("El resto del documento se organiza como sigue. La Sección 2 revisa el estado del arte en detección de trastornos de salud mental con PLN. La Sección 3 desarrolla el marco teórico (BoW, TF-IDF, VSM, similitud coseno, clasificación de Rocchio, autómatas y transductores, y métricas de evaluación). La Sección 4 describe el montaje experimental: hardware, software, corpus, objetivo y los cuatro experimentos. La Sección 5 presenta el resultado general y su relación con la hipótesis. La Sección 6 ofrece el análisis crítico de resultados, centrado en la clase Ideación Suicida. La Sección 7 fortalece la evaluación mediante validación cruzada y la comparación con un modelo base de Naïve Bayes. La Sección 8 discute limitaciones, consideraciones éticas y trabajo futuro. La Sección 9 concluye y la Sección 10 reúne el aparato crítico."));
children.push(new Paragraph({ children: [new TextRun("")], pageBreakBefore: true }));

// ============================ 2. ESTADO DEL ARTE ============================
children.push(H1("2. Estado del Arte y Trabajo Relacionado"));
children.push(P("La detección de trastornos de salud mental a partir de texto se ubica en la intersección entre el PLN y la psicología. La revisión de Teferra et al. (2024) organiza el campo en cinco subtareas: clasificación (distinguir estados con y sin trastorno), clasificación de severidad, identificación de síntomas, evaluación de riesgo y análisis personalizado. El presente trabajo aborda la primera, extendida a cuatro categorías."));
children.push(H2("2.1 Enfoques basados en marcadores lingüísticos y conteo de palabras"));
children.push(P("La línea más antigua y más interpretable se apoya en marcadores lingüísticos: frecuencias de pronombres en primera persona, términos de afecto negativo, palabras absolutas («siempre», «nunca», «nada») y categorías léxicas asociadas a la rumiación. Estos enfoques, vinculados a herramientas como LIWC, demostraron que el lenguaje depresivo presenta regularidades estadísticas medibles. La ponderación TF-IDF puede entenderse como una generalización no supervisada de esta idea: asigna pesos altos a los términos discriminativos del corpus sin necesidad de un diccionario psicológico predefinido."));
children.push(H2("2.2 Enfoques basados en aprendizaje automático clásico"));
children.push(P("Una segunda generación de trabajos combinó representaciones vectoriales (TF-IDF, n-gramas) con clasificadores como Naïve Bayes, regresión logística o máquinas de soporte vectorial (SVM). Tadesse et al. (2019) alcanzaron un F1 de 0.93 en depresión sobre Reddit con combinaciones de rasgos léxicos; sistemas posteriores de detección de ideación suicida reportaron exactitudes cercanas al 95 % integrando TF-IDF con Word2Vec y modelos híbridos. Estos resultados fijan el techo práctico contra el cual conviene contrastar una línea base no supervisada como la nuestra."));
children.push(H2("2.3 Enfoques neuronales y modelos de lenguaje"));
children.push(P("La generación más reciente emplea word embeddings, redes profundas y modelos de lenguaje de gran escala (transformers). Estos modelos capturan relaciones semánticas que el VSM no puede representar —sinonimia, contexto, negación— y suelen superar a los métodos clásicos en exactitud. No obstante, Teferra et al. (2024) advierten que su opacidad agrava preocupaciones de interpretabilidad, privacidad y sesgo, especialmente delicadas en salud mental. La interpretabilidad de los métodos clásicos, que permite explicar cada decisión a partir de pesos de términos, es por tanto una ventaja relevante en este dominio."));
children.push(H2("2.4 Posicionamiento de este trabajo"));
children.push(P("Nuestro sistema se inscribe en la primera y segunda líneas, pero con una restricción autoimpuesta: no entrenar modelos. Emplea centroides de clase (clasificación de Rocchio) sobre vectores TF-IDF, un método con respaldo teórico (Manning et al., 2008) y, curiosamente, validado de forma indirecta por estudios recientes: el análisis de centroides de subreddits de Bauer et al. (2024) confirma que las publicaciones de r/SuicideWatch tienden a situarse cerca del centroide de r/Depression, lo que anticipa la confusión entre ambas clases que observaremos empíricamente."));
children.push(new Paragraph({ children: [new TextRun("")], pageBreakBefore: true }));

// ============================ 3. MARCO TEÓRICO ============================
children.push(H1("3. Marco Teórico"));
children.push(P("Esta sección define la teoría base del sistema siguiendo el enfoque clásico de Recuperación de Información de Manning, Raghavan y Schütze (2008), complementado con la teoría de autómatas de Kleene (1956)."));

children.push(H2("3.1 Bolsa de palabras (Bag of Words)"));
children.push(P("La representación de Bolsa de Palabras descompone cada documento en el conjunto de los términos que contiene, ignorando el orden. El vocabulario completo del corpus define las dimensiones de un espacio vectorial: cada término único es un eje ortogonal. Un documento se convierte así en un vector cuyas componentes cuantifican la presencia de cada término. La asunción de independencia entre términos —la «bolsa»— es una simplificación fuerte que descarta la sintaxis, pero a cambio produce una representación numérica tratable y sorprendentemente efectiva para tareas de tópico."));

children.push(H2("3.2 Ponderación TF-IDF"));
children.push(P("No todos los términos son igual de informativos. La ponderación TF-IDF combina dos factores complementarios:"));
children.push(bullet([ b("Frecuencia de término (TF). "), t("Mide la importancia local de un término en un documento. Se emplea la variante sublineal 1 + log(tf), que evita que una palabra repetida muchas veces domine el vector de forma desproporcionada: la diferencia entre aparecer 1 y 10 veces es relevante, pero entre 100 y 110 es marginal.") ]));
children.push(bullet([ b("Frecuencia inversa de documento (IDF). "), t("Mide la especificidad global de un término mediante log(N / df), donde N es el número de documentos y df el número de documentos que lo contienen. Penaliza palabras ubicuas —cuyo IDF tiende a cero— y premia las raras y discriminativas. Se aplica además un suavizado (sumar 1 al numerador y al denominador) para evitar divisiones por cero.") ]));
children.push(P([ t("El peso final es el producto "), code("tfidf = tf × idf"), t(". Intuitivamente, TF representa la «popularidad» de un término y IDF su «sofisticación» o especificidad; su producto destaca términos que son frecuentes en un documento concreto pero raros en el corpus, es decir, los que mejor caracterizan a ese documento.") ]));

children.push(H2("3.3 Modelo de Espacio Vectorial y similitud coseno"));
children.push(P("Una vez ponderados, los documentos son vectores en un espacio de miles de dimensiones. La similitud entre dos vectores se mide por el coseno del ángulo que forman:"));
children.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 80, after: 120 },
  children: [new TextRun({ text: "sim(A, B) = cos(θ) = (A · B) / (‖A‖ × ‖B‖)", italics: true, size: 24 })] }));
children.push(P("El numerador es el producto punto; el denominador, el producto de las normas euclidianas. La división normaliza la magnitud, de modo que el coseno depende solo de la dirección de los vectores: un texto corto y uno largo sobre el mismo tema resultan similares aunque sus magnitudes difieran. Un coseno de 1 indica vectores idénticos en dirección (máxima similitud); 0 indica ortogonalidad (sin términos en común). Como los pesos TF-IDF no son negativos, el coseno se mantiene en el rango [0, 1]. Esta independencia de la magnitud es deseable en RI, pero, como se argumentará en la Sección 6, introduce una debilidad ante textos muy cortos, cuyo vector es tan disperso que su coseno con cualquier referencia tiende a ser bajo (De Boom et al., 2015)."));

children.push(H2("3.4 Clasificación por centroides (método de Rocchio)"));
children.push(P("Para clasificar se representa cada clase mediante un centroide: el vector promedio de todos los documentos de entrenamiento de esa clase, es decir, su «centro de masa» en el espacio vectorial. Un texto nuevo se asigna a la clase cuyo centroide presenta mayor similitud coseno (regla de argmax). Si la similitud máxima no supera un umbral mínimo, el texto se considera Neutral (regla de rechazo). Este método, conocido como clasificación de Rocchio o del centroide más cercano (Manning et al., 2008, cap. 14), tiene dos ventajas decisivas para este proyecto: es no supervisado en el sentido de que no requiere optimización iterativa, y es interpretable, pues los términos de mayor peso de cada centroide revelan el vocabulario característico de la clase, que puede inspeccionarse y discutirse."));

children.push(H2("3.5 Autómatas y transductores de estados finitos"));
children.push(P("La extracción de información estructurada se apoya en dos formalismos clásicos de la teoría de la computación. Una expresión regular describe un lenguaje regular y es equivalente a un Autómata Finito (FSA), máquina abstracta que acepta o rechaza cadenas según alcance o no un estado final (Kleene, 1956). Un Transductor de Estados Finitos (FST) extiende el autómata con un alfabeto de salida Γ: por cada símbolo de entrada que consume, emite uno de salida, comportándose como una máquina de traducción. En este proyecto, el FSA reconoce expresiones de duración de síntomas («for three weeks») y el FST las traduce a un valor canónico normalizado en días, transformando texto libre en un dato estructurado y comparable."));

children.push(H2("3.6 Evaluación: matriz de confusión y métricas"));
children.push(P("El desempeño se mide comparando predicciones con etiquetas reales mediante una matriz de confusión, de la que se derivan, por clase y bajo un esquema uno-contra-el-resto:"));
children.push(bullet([ b("Precisión = TP / (TP + FP). "), t("De lo que el sistema marcó como una clase, qué proporción acertó. Penaliza las falsas alarmas (errores de Tipo I).") ]));
children.push(bullet([ b("Exhaustividad (Recall) = TP / (TP + FN). "), t("De lo que realmente pertenecía a una clase, qué proporción encontró. Penaliza las omisiones (errores de Tipo II), que en este dominio son los falsos negativos críticos.") ]));
children.push(bullet([ b("F1 = 2·P·R / (P + R). "), t("Media armónica de ambas; penaliza con dureza cualquier desbalance entre precisión y exhaustividad.") ]));
children.push(P("Manning et al. (2008, cap. 8) advierten que la exactitud (accuracy) es engañosa con clases desbalanceadas: un clasificador trivial que asignara todo a la clase mayoritaria podría exhibir alta exactitud y, sin embargo, una exhaustividad nula en las clases de interés. Por eso se prefieren precisión y exhaustividad, y se reportan promediadas en su variante macro (cada clase pondera igual). En contextos de detección de riesgo, la exhaustividad es la métrica de oro, pues minimizar los falsos negativos —no señalar a quien sí está en riesgo— es la prioridad ética y clínica."));
children.push(new Paragraph({ children: [new TextRun("")], pageBreakBefore: true }));

module.exports = children;
